sudo: false
language: node_js
node_js:
 - "4"
 - "5"
 - "6"
 - "7"
 - lts/*
 - stable
addons:
 apt:
  sources:
   - ubuntu-toolchain-r-test
  packages:
   - gcc-4.8
   - g++-4.8
env:
 - CC=gcc-4.8 CXX=g++-4.8
